php-apache:
  build: .
  links:
    - "mysql"
  ports:
    - "80:80"
  # volumes:
  #   - ~/Project/xxx/code:/var/www/html

mysql:
  build: ./mysql
  expose:
    - "3306"
  environment:
    MYSQL_DATABASE: docker
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker
    MYSQL_ROOT_PASSWORD: docker
  # volumes:
  #   - ~/docker-volumes/mysql/xxx:/var/lib/mysql
